
server:
  port: 8080

message:
  topic:
    name: my_topic_msa_booker

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: booker-service
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-id-oring
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'root'
    url: 'jdbc:mariadb://localhost:3306/msa'
    password: 'eddy'
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        storage_engine: innodb
    defer-datasource-initialization: true